# 应用配置
server:
  port: 9002

# Dubbo配置
dubbo:
  application:
    name: dubbo3-provider
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    parameters:
      namespace: public
      group: DEFAULT_GROUP
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.example.provider.service  # 明确指定扫描包

